name = "SatelliteToolboxSgp4"
uuid = "ba14ac17-bfc9-4710-a76f-b32930ef2339"
license = "MIT"
desc = "The SGP4/SDP4 orbit propagator for Julia"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SatelliteToolboxTle = "7ff27aeb-5fff-4337-a9ee-a9fe6b7ed35e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
SatelliteToolboxTle = "1"
StaticArrays = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[targets]
test = ["Test", "DelimitedFiles", "Printf"]
