name = "SatelliteToolboxSgp4"
uuid = "ba14ac17-bfc9-4710-a76f-b32930ef2339"
license = "MIT"
desc = "The SGP4/SDP4 orbit propagator for Julia"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
SatelliteToolboxTle = "7ff27aeb-5fff-4337-a9ee-a9fe6b7ed35e"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
SatelliteToolboxBase = "0.1"
SatelliteToolboxTle = "1"
SnoopPrecompile = "1"
StaticArrays = "1"
julia = "1.6"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles", "Printf"]
